### ISSUE TITLE
[Suggestion]: A way for players to add and pick their own skins that don't involve naming the statue

### ISSUE THREAD

**Issue by Greg727** [Fuzss/strawstatues#1]
### Suggestion (Required)

The reason this would be better is because the naming feature is all over the place,

EX: Typing Mario got me Luigi instead.

EX: Typing Scorpion gives you the pink panther

I think it would be better if there was someway to add our own skins and to make it so that naming the statue doesn't effect the skins

**Comment by JustSomeGamer000** [comment]
I really want this added! it's the only thing holding this mod back...

**Comment by Fuzss** [comment]
Added in v4.0.4. Since there were two text boxes for changing the name before, now one of those only changes the name while the other controls the skin.
