### ISSUE TITLE
[Suggestion]: Scale and More rotation

### ISSUE THREAD

**Issue by A00826925** [Fuzss/strawstatues#10]
### Suggestion (Required)

i love this mod! placing characters in the world is fun, however there could be a couple more options for editing, for example:
- Scaling: use the normal player proportions and scale them to any size (not like the small model which has a big head)
- Rotation on all axys: to allow more complex poses, like laying down, falling, flying, etc.

**Comment by Fuzss** [comment]
Scale I probably won't do, but rotations make sense, like for players that are supposed to swim or elytra flying.

**Comment by A00826925** [comment]
for scale i was thinking of using the statues as figurines, like creating small scenarios on a table or something

**Comment by Fuzss** [comment]
Alright, kinda went the other way now: Scale option is implemented, works really great with the statues, you were right.
Just released a new version with that (v4.0.10).

I'm testing rotations on all axis, but really nailing the implementation is a bit tricky, so not sure when that'll be ready.

**Comment by A00826925** [comment]
scale seems to be working fine! thanks for the implementation!

**Comment by Fuzss** [comment]
All implemented now in v4.0.11.
