### ISSUE TITLE
[Bug]: Server not opening edit menu in survival

### ISSUE THREAD

**Issue by A00826925** [Fuzss/strawstatues#11]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

v4.0.8

### Notes (Required)

"When in a singleplayer world I can open the statue in survival and creative
When in a locally hosted server, I cannot open the statue in survival, but I *can* in creative.

For some reason in the server environment, while in survival trying to open the statue it places my armor set onto the statue"

the previous comment was from the comment section in the mod page, im not that guy but im experiencing the same issue.

**Comment by Fuzss** [comment]
you have quark installed haven’t you?

**Comment by A00826925** [comment]
yes i do, i could also send my whole mod list if you need it

**Comment by Fuzss** [comment]
No need to, it's an incompatibility with Quark.

**Comment by Fuzss** [comment]
Please try again with v4.0.9 that was just released. Is your issue fixed?

**Comment by A00826925** [comment]
Im currently testing in singleplayer, and i still just give the statue my armor when shift+right clicking, was the method of opening the menu changed?

**Comment by A00826925** [comment]
holding the stick seems to be working perfectly!
