### ISSUE TITLE
[Crash]: Out of Bounds on startup (low priority)

### ISSUE THREAD

**Issue by A00826925** [Fuzss/strawstatues#12]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

v4.0.10

### Notes (Required)

Random crash while using the following mod pack: https://www.curseforge.com/minecraft/modpacks/better-forever

Kinda random since it fixed itself on the next run, but might as well share it.

### Crash Report (Required)

https://gist.github.com/A00826925/9b476f9bdaf2e0018d127509c38fbdab

**Comment by Fuzss** [comment]
That's a concurrency issue, those come and go randomly. I'll include a fix in the next version.

**Comment by azridere** [comment]
On Quilt I get this randomly while hovering over items? https://mclo.gs/MyYBDOQ

**Comment by Fuzss** [comment]
@azridere  please open a separate issue

**Comment by Fuzss** [comment]
Fixed in v4.0.11.
