### ISSUE TITLE
[Bug]: Menu not opening

### ISSUE THREAD

**Issue by realovee** [Fuzss/strawstatues#13]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

3 newest versions

### Notes (Required)

Nothing is happend when i placing statues. Just random pose, not menu. I play with supplementaries, but i also try without this mod. I also try change version from Forge to farbic and menu didnt work too.

**Comment by realovee** [comment]
ok nevermind, i search and find that now i need to take sticks. You shoud update discription on curseforge :D

**Comment by Fuzss** [comment]
I hoped people would notice the description on the straw statue item haha.
