### ISSUE TITLE
[Bug]: Invisible

### ISSUE THREAD

**Issue by SilvioOS** [Fuzss/strawstatues#14]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.0.10

### Notes (Required)

I'm using a custom made modpack and the straw statues that i try to spawn are actually invisibles. Idk it may be an incompability with other mods? Maybe with CEM and CIT port from optifine?
![image](https://user-images.githubusercontent.com/100525471/221660046-79abe018-f8c3-455e-80f1-ed084b915957.png)

**Comment by SilvioOS** [comment]
I even tried disabling CIT and CEM but this doesn't work anyway. I'm actually clueless

**Comment by SilvioOS** [comment]
I've found the problem. I'm sorry i'm not used to fabric settings, i had a config that didn't show armor stand and statues aswell. Hope that this post may help someone with the same problem to figure it out faster at least. Greetings

**Comment by Fuzss** [comment]
No worries! What sort of config from what mod is that?
