### ISSUE TITLE
[Bug]: Statue does not spawn with my skin?

### ISSUE THREAD

**Issue by lSherozl** [Fuzss/strawstatues#17]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.0.10

### Notes (Required)

I dont understand if there is some mod incompatability but I have to crouch and hit it with a stick first to get the menu to open up, and then it takes the stick into its hand and I cant remove it, and the statue remains with the straw and not my skin?
<img width="741" alt="image" src="https://github.com/Fuzss/strawstatues/assets/65663746/b16aa17f-47ff-40a7-88b3-3338741b808b">

**Comment by lSherozl** [comment]
For the stick I just have to be careful not to touch the arms with it, but the skin of the statue does not change

**Comment by lSherozl** [comment]
Never mind you have a dedicated name section, where if you change the name there it changes the statues skin, dont know why mario gives you Luigi

**Comment by lSherozl** [comment]
I am wondering if you are able to read this, How do u access all the models, I wish I could see what they all look like, like a book that shows all the possible models you can assign?

**Comment by Fuzss** [comment]
This is probably the best site: https://namemc.com/

**Comment by lSherozl** [comment]
Thank you

**Comment by Zellneriusikus** [comment]
Even taking skins from the NameMC site, they don't work on straw statues
