### ISSUE TITLE
[Suggestion]: Have a way to lower the name on top of the statue to a lower height

### ISSUE THREAD

**Issue by lSherozl** [Fuzss/strawstatues#18]
### Suggestion (Required)

<img width="579" alt="image" src="https://github.com/Fuzss/strawstatues/assets/65663746/1101f1ac-3662-403d-92fa-40db8a80fbd3">

The model that has the name "Sakura" is from your mod, the other mod is the statues mod, when they assign a name, and you display the name, its near the head of the statue and looks natural to the player, your model kind of keeps the name to a larger distance from the top of the head. If this was customizable, that would be great!

**Comment by lSherozl** [comment]
<img width="1006" alt="image" src="https://github.com/Fuzss/strawstatues/assets/65663746/bf78e4f3-0fc0-4fdd-828f-32f7cc27576e">
This is what the statue models look like, they mimic what a players name height would be like in Minecraft as a reference

**Comment by lSherozl** [comment]
Feel free to let me know if this is feasible or possible, thank you, really do love the mod and the hard work you do!

**Comment by Fuzss** [comment]
Fixed in v4.0.11.
