### ISSUE TITLE
[Bug]: Client crash after renaming statue

### ISSUE THREAD

**Issue by SebSemos** [Fuzss/strawstatues#2]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.0.0

### Notes (Required)

I get Kicked out of my server when renaming a statue with an invalid username. 
Can't log back. Reboot of the server does'nt fix it. 

### latest.log (Optional)

https://pastebin.com/bTxRcpxe

**Comment by Fuzss** [comment]
Please run the game with https://www.curseforge.com/minecraft/mc-mods/not-enough-crashes
and submit a deobfuscated crash-report

**Comment by SebSemos** [comment]
Sadly it does not bring any report as neither the game or the server crash. I just get kicked :/

**Comment by Fuzss** [comment]
Ok, then please just send the log from above again with the not enough crashes mod installed

**Comment by Fuzss** [comment]
Please test v4.0.1 if it fixes your issue.

**Comment by SebSemos** [comment]
Yep, it's working fine with v4.0.1 ;) :)
