### ISSUE TITLE
[Bug]: conflicting functionality of segments

### ISSUE THREAD

**Issue by DadoIrie** [Fuzss/strawstatues#21]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

8.0.1

### Notes (Required)

When having either one or both of them [Straw Statues](https://github.com/Fuzss/strawstatues) & [Armor Statues](https://github.com/Fuzss/armorstatues) active following issue occurs:
It breaks the functionality of [segmented](https://github.com/csumpasd/segmented)

Only happens when the first hotbar slot is selected: 
- pressing 1 doesn't trigger the selection of the first segment
- pressing 2 does trigger the 2nd segment, but pressing 1 does not select the 1st slot of the 2nd segment
- pressing 3 does trigger the 3rd segment selection, but does not select the 1st slot of the 3rd segment when pressing 1

When any other slot is selected switching slots works without issues, just when having again the first slot selected this issue is triggering again.

Will post this also in the [segments Github issues](https://github.com/csumpasd/segmented/issues/12) and link the issues so that both sides know of it and figure out which of them is more suited or even the one causing it and hopefully fixing it.

**Comment by Fuzss** [comment]
It is completely unrelated to the statues mods. I just don't want to have a bunch of libraries when I need to share code between two mods, so it all ends up in Puzzles Api.
