### ISSUE TITLE
[Suggestion]: set idle pose at the default pose for straw statues.

### ISSUE THREAD

**Issue by pantsguyapp** [Fuzss/strawstatues#24]
### Suggestion (Required)

Instead of generating random poses for the statues everytime it is placed in the world, you should have a default pose for it, the idling player pose seems as shown in the pictures below seem really fit for the statue.
![CI2zFFs](https://github.com/Fuzss/strawstatues/assets/92203672/1ebf43a9-5cb2-4299-90e7-9dfd10aa8d54)
![Statues-Mod-2](https://github.com/Fuzss/strawstatues/assets/92203672/a4fc6080-3287-4b02-b787-f309c85f45e0)
![download](https://github.com/Fuzss/strawstatues/assets/92203672/bd3094af-a609-46bd-8182-b42deed3d4f4)

**Comment by Fuzss** [comment]
You can already do that by crouching while placing the statue.

**Comment by pantsguyapp** [comment]
open it again pls, below is how I wanted it to be.
![2023-10-16_09 02 00](https://github.com/Fuzss/strawstatues/assets/92203672/d72452ca-1ab3-4c8f-912a-edba5a30aac3)
The default pose when shift-clicked is on the right, but what I wanted is on the left, literally everything is set to 0 for the statue.
