### ISSUE TITLE
[Bug]: EOFException when changing anything in Style Menu

### ISSUE THREAD

**Issue by eliasschuetz** [Fuzss/strawstatues#26]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.1

### Notes (Required)

Current behavior: When attempting to change any of the checkbox settings within the menu, my server boots me with an EOFException, shown in the included screenshot.
Steps to reproduce:
1. Place statue
2. Open menu
3. Navigate to Style tab
4. Change any checkbox option
5. Booted from server
Excepted: Changing options within the menu not causing server boot.

![Screenshot 2023-10-28 162203](https://github.com/Fuzss/strawstatues/assets/106632977/6936a134-1ccd-488f-a584-35b979796e98)

**Comment by RuneTome** [comment]
I'm also having the same issue, with the added problem that when I try to change the skin, it also boots me from the server.
