### ISSUE TITLE
[Bug]: Crashing my Client if i try to rename Puppet

### ISSUE THREAD

**Issue by Regnak85** [Fuzss/strawstatues#3]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.0.0.

### Notes (Required)

Placed Statue.
Moved it around a bit
Tried to give it a Name -> Crash Client (Not the Server)

### latest.log (Optional)

https://gist.github.com/Regnak85/a79745a2c645f6cddb606bcce904e9e7

**Comment by Fuzss** [comment]
Please test v4.0.1 if it fixes your issue.

**Comment by Fuzss** [comment]
Fixed according to https://github.com/Fuzss/strawstatues/issues/2
