### ISSUE TITLE
What is the right button

### ISSUE THREAD

**Issue by Jifterlegend30485** [Fuzss/strawstatues#32]
### Mod Loader (Required)

Forge

### Minecraft Version(s) (Required)

1.20.4

### Mod Version(s) (Required)

49.0.30

### Minimal Setup (Required)

Yes

### Notes (Required)

I am confused what the right button is. I don't know where it is, and I can't use this mod now because I don't know what it is

### latest.log (Required)

https:gist.github.com/jifterlegend30485

**Comment by Fuzss** [comment]
Right mouse button + empty hand.
