### ISSUE TITLE
[Suggestion]: costum skin

### ISSUE THREAD

**Issue by NikoHite** [Fuzss/strawstatues#33]
### Mod Loader (Optional)

⸺

### Suggestion (Required)

i have suggestion, can you make the straw statue can use import skin, so other than use skin from nickname, player can just import their skin to game

**Comment by Fuzss** [comment]
No, the statues use the same player heads do meaning only existing player skins are supported.

**Comment by PalgamingHD** [comment]
> No, the statues use the same system player heads do meaning only existing player skins are supported.

Even Minecraft heads allow for custom skins

**Comment by Fuzss** [comment]
How? The wiki suggests the skin must be present on textures.minecraft.net, which only stores skins currently used / having been used by valid Minecraft players. https://minecraft.fandom.com/wiki/Player.dat_format/Player_Heads

The statues do keep the skin of the player when they are created though, even if the player changes their skin later on in case you are referring to that.

**Comment by PalgamingHD** [comment]
I'm not really sure the exact method but https://namemc.com/ definitely uses other skins. But I believe it is (as you said) old player skins but are still accessible. But if it's possible to integrate that, that would be cool

**Comment by Fuzss** [comment]
Yeah, the old skins will stay on the state as mentioned if they were the current one when the statue was created. No plans to go beyond that though. You can get old skins not currently used by a player via commands on the statue though.

**Comment by PalgamingHD** [comment]
Oh nice, that's good enough for me. Is there a specific command format for that?

**Comment by Fuzss** [comment]
Just like player heads. Probably best to look at it via `/data`.
