### ISSUE TITLE
[Bug]: Fieldsize error in multiplayer while applying a skin on a straw statue

### ISSUE THREAD

**Issue by Saperke** [Fuzss/strawstatues#35]
### Mod Loader (Required)

Forge

### Minecraft Version(s) (Required)

1.19.2

### Mod Version(s) (Required)

v4.0.12-1.19.2

### Minimal Setup (Required)

Yes

### Notes (Required)

Set a LAN server in creative. (it's faster but also work in survival)
place a straw statue in front of you
let another account or friend connect
then proceed to load a skin from the "model parts" section. ( for example "blank" wish as a skin )
The second account or friend will be kicked out of the game with a field size error wichever RAM is allocated.

Note: we notice that in a LAN server of three people or me, a friend and my alt. Only one of two "joiners" "loose connection" with the "fieldsize is to long" error

### latest.log (Required)

https://gist.github.com/Saperke/9b5c975d7ab0a29ae687692194d8c570

**Comment by Fuzss** [comment]
Should be fixed in v4.0.13.
