### ISSUE TITLE
[Crash]: Locks me out of server if I rename a statue above 16 letters

### ISSUE THREAD

**Issue by CTN-0452-9** [Fuzss/strawstatues#4]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

v4.0.3

### Notes (Required)

I should note that this does not actually crash the server, it just kicks me as well as any other player who tries to join the server.

1. Click the statue
2. Begin to change its name
3. Type a name that is 17 characters
4. Exit the statue UI
5. GG

### Crash Report (Required)

There is no crash report, as it didn't crash the server, it just disconnects me the moment I join

**Comment by Fuzss** [comment]
I need the log then, from client and server.

**Comment by Fuzss** [comment]
Any update on the logs?

**Comment by Darkweaver66** [comment]
One of my players caused the same issue last night. "fixed" by removed the mod and reloading the server without it, then reloading it again with it back on, but that removes all straw statues in doing so. just replicated it myself to submit a server log. the Server has a log but Client doesn't generate one from it. Recorded how to replicate + the disconnect error instead for that one.

**Mod Loader (Required)**
Forge

**Minecraft Version (Required)**
1.19.2

**Mod Version (Required)**
v4.0.3

**Notes (Required)**

- To replicate, place a statue, and edit its name to be 17+ characters long. The client hangs for a few seconds then disconnects stating "Internal Exception: io.netty.handler.codec.DecoderException: The receieved string length is longer than maximum allowed (17 > 16)"

- The server remains up throughout, and googling that error in isolation suggests that it is usually caused when players with glitched names join servers, causing everyone to disconnect. As the statue remains in game though, it causes the issue to continue until the mod is removed to force removal of the statue.

Crash Report (Required)
No crash report available as the server remains open, but refuses to allow players to connect

latest.log (Optional)
[latest.log](https://github.com/Fuzss/strawstatues/files/9964043/latest.log)

Linked below is a recording of the error occuring in game, and the steps to replicate it, taken with Xbox app on PC and uploaded to Drive
https://drive.google.com/file/d/1LdeI7-6aMDWykLkiTUDUBVP6a0apapPT/view?usp=share_link

**Comment by CTN-0452-9** [comment]
> Any update on the logs?

My fault gansta I forgot all about this after it was fixed by doing the same thing Darkweaver66 did

**Comment by Fuzss** [comment]
Should be fixed in v4.0.4. Also if a server locked you out before you should now be able to get back in.
