### ISSUE TITLE
[Crash]: when using the "scale and rotations" option the game will crash immediately 

### ISSUE THREAD

**Issue by TehRubrDuk** [Fuzss/strawstatues#44]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.21.1

### Mod Version(s) (Required)

v21.1.0

### Minimal Setup

Yes

### Notes (Required)

Open the config screen using shift + right click, every option works perfectly fine, click on the "scale and rotations" option and the game will immediately crash to launcher. 

The game crashed whilst rendering screen
Error: java.lang.NoSuchMethodError: 'void fuzs.puzzleslib.api.client.gui.v2.components.GuiGraphicsHelper.blitNineSliced(net.minecraft.class_332, net.minecraft.class_2960, int, int, int, int, int, int, int, int, int, int)'

crash log the game spits out

### Crash Report (Required)

https://gist.github.com/TehRubrDuk/c036616e6e161bcfeea172784dfa85cc

**Comment by Fuzss** [comment]
Update Puzzles Lib to the latest version. 👍

**Comment by TehRubrDuk** [comment]
works perfectly now thank you!

**Comment by TehRubrDuk** [comment]
Also just a thought an update allowing the statue to have the skin of a player but the texture of a block would be wonderful, not sure how to make suggestions but you might see this :)

and if possible added to all versions of the mod too would be lovely, for example from the old classic statues mod which is no longer supported or updated
![Screenshot 2024-12-17 014838](https://github.com/user-attachments/assets/ee9b8621-8af3-4b55-95d6-b7356e5093d4)
