### ISSUE TITLE
[Suggestion]: Remove copy/pasting text and limit statue names to only 16 characters on text entry

### ISSUE THREAD

**Issue by Darkweaver66** [Fuzss/strawstatues#5]
### Suggestion (Required)

I've been thinking about potential solutions to the open bug report regarding being kicked from server's when a statue with 17+ character names are present, which I added a report to after experiencing the crash here: https://github.com/Fuzss/strawstatues/issues/4#issuecomment-1307652706

Looking further into it, its unlikely to be "fixable" as its a behaviour from Vanilla minecraft, used to handle players joining with glitched usernames. However, is it possible to both limit the number of characters a player can type into the field, and also remove the ability to copy/paste into the name field? (on testing, it can happen with any number of characters if you paste a large string of text in). If so this would prevent players being able to use your mod to stop servers from being able to be logged in to, as it would implement a prevention proir to the name bug occuring.

**Comment by Fuzss** [comment]
Should be fixed in v4.0.4.
