### ISSUE TITLE
[Crash]: crash.

### ISSUE THREAD

**Issue by JustSomeGamer000** [Fuzss/strawstatues#6]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.0.4

### Notes (Required)

Tried opening the game with 81 mods (including optifine) but wouldn't open.

Took all mods out including optifine so it was just the one mod.

Still crashed.

### Crash Report (Required)

it didn't create a crash report... :(

**Comment by Fuzss** [comment]
Well do you have puzzles Lib my library installed? Also the latest log will be there I need that

**Comment by JustSomeGamer000** [comment]
1. yes I did have puzzles lib installed.

2. you mean like this log?

‹      ÿ­T[oÓ0~Gâ?x<Ñ:÷¬
šÐÔ(jÓ±tŒn*79É\;²“vë¯Ç¹Œ
´¡
ÈCrâsý¾sŽ/MÛç[S7Mdô=G÷L[–{….3B™6ö?Ì”æ;œñHV¯””,¼'­ MgÃÉñ™?ø4:½òÐ”Gw$JÆ(K<DD"Ñe·[JŒdÐAŸKY<ƒêO¸®ÛAÝî„¤œu>6»1	tmØ1+ƒD©è ·<S¡äò$%·„×Ëã<’‚,O9ÉTÊ%Vo‰‹Ê‘H	…|±ë²ñûaÌ"¸iÊ«ÎÊ’Fä&11¦Môp[1q~ßŽ.kï0)çü;(tïÛ§R„)VŒU˜ÙùbïŸœÅù¢ð‡ßÍ‹@×ýýñ~2O¬Å<)¦›d±YìüÍ—¿On*ï›º Ó±Ûèénßí÷MÝ©KSç·¹":“ä·Í™€ˆ„ê¼iç\5S5ãMM•2ÎR\}½ëÌƒfTÊ,üúkÏ~ñú(x™wƒâžÒZqïžÿô¯fPïé6,½çXW¯_]>6›vï?Í¦¡c÷Þ¶Ÿ*"Ö!>„ž¥#YQÔƒ»![‚Zîq¨l-´¾ES
.y\¼C³ SñT!Õ ‡×ˆd‘kß{©ƒ±]ë70</h¬¨Â3%|PÂ\&g)T¬ Ä–† )(4ÀœM8‰žÊjÿsVt1>A1MN<T2eæiO«WK»[-­]-­]-í~´ªgZ.`Ka·º‹»j¦hõi¸:[•ÒÛxCÄÓ2lç@{Ñ¡þÿy/»!*ËçÂxª|óÙå«‘VE7ëŠONG«Áä8•H
*MÉ:…Ç“8†ó[’ŒÞ¨-È9Kà„ï@@„¦ãocåZÞÊ2Ô.è‘Úì €—"„£¿ixJ×‚
RSW€&ë¤y“Tkj©S4r·–ÛÖ÷
µ=;z¸Ã#¶=LÆ#þhóùÌ¾lÁ(£%)Ý+º $ÏõÝD

**Comment by Fuzss** [comment]
Yeah, that looks incomplete though. And preferably like this: https://gist.github.com/Fuzss/866b384d353912986e37b17eeef7a285

**Comment by JustSomeGamer000** [comment]
soooo like this?

https://gist.github.com/JustSomeGamer000/b555f254f154787e447ad2bd0ae7ff0d

**Comment by Fuzss** [comment]
Ok, thanks. It just doesn't tell me anything unfortunately though...

**Comment by JustSomeGamer000** [comment]
maybe its a problem with forge?

i'm using 43.1.52

**Comment by Fuzss** [comment]
I'll check that later. In the meantime, can you also send your debug.log?

**Comment by JustSomeGamer000** [comment]
https://gist.github.com/JustSomeGamer000/cca16099db528543412d0d1b2c430790

this should be it.

**Comment by Fuzss** [comment]
That doesn't seem to be related, the game loads fine in that log.
I just compiled a new version (v4.0.5), maybe it works for you?

**Comment by JustSomeGamer000** [comment]
![2022-12-01_17 18 49](https://user-images.githubusercontent.com/118029435/204964975-cd941fb6-4bef-4067-ab6c-082ff015c59f.png)

**Comment by Fuzss** [comment]
Awesome haha
