### ISSUE TITLE
[Bug]: Straw statues lose skin

### ISSUE THREAD

**Issue by notIkibo** [Fuzss/strawstatues#7]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

404

### Notes (Required)

since the new update where name and skin name is seperated. Every time I restart the server, the statues lose their skin name and I have to rename them

**Comment by Darkweaver66** [comment]
Was going to raise same issue. New version no longer causes server-locking bug, but the changes to skin management cause the text field to return to blank after a server restart. Same as above but on Forge, mod version 4.0.4

**Comment by Fuzss** [comment]
Fixed in v4.0.5.
